### ISSUE TITLE
Thoughts on public API

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#12]
#11 is a good start for gathering requirements for public API.

**Comment by gavv** [comment]
What we need so far in the API:

* set log level and handler
* create sender and receiver
* create RTSP server that allows user to handle new sessions manually
* send and listen SDP/SAP announcements
* sender should be able to connect to both RTP address and RTSP url
* simple blocking I/O for sender and receiver
* optional zero-copy I/O for them
* probably, optional non-blocking I/O
* probably, ability to share single network loop for multiple objects
* options to configure sender and receiver parameters, like payload type, FEC scheme, etc.

**Comment by baranovmv** [comment]
We should implement idle mode not later than (simultaneously with) SDP/SAP announcement publishing, otherwise roc sinks would send 2 Mb/s traffic to each discovered sink inputs. Just like pulseaudio do so far.

**Comment by gavv** [comment]
Issue for the idle mode: #72

**Comment by gavv** [comment]
Technically, our public API will provide the following:

* public headers: roc/sender.h, roc/receiver.h, roc/log.h
* dynamic library: libroc.so

libroc will dynamically link all system libraries and statically link all roc modules (like libroc_core.a) and builtin third-party libraries (like libuv.a) enabled with --with-3rdparty option. It should be enough to link just with libroc.so for the user.

We also need to export library version in headers and in soname, and use properly naming when installing library (see #35).

**Comment by gavv** [comment]
> We should implement idle mode not later than (simultaneously with) SDP/SAP announcement publishing, otherwise roc sinks would send 2 Mb/s traffic to each discovered sink inputs. Just like pulseaudio does so far.

This traffic should be prevented by module-suspend-on-idle. Tunnel sinks and sources should support this as well. Not sure why this didn't work, maybe the module was not loaded or timeout was too high. Need to recheck.

We still need to add suspend/resume support for both roc sink and sink input.

**Comment by gavv** [comment]
> set log level and handler
> create sender and receiver

Done.

> create RTSP server that allows user to handle new sessions manually
> send and listen SDP/SAP announcements
> sender should be able to connect to both RTP address and RTSP url

Will be addressed in separate issues.

> simple blocking I/O for receiver
> optional zero-copy I/O for them

Done.

> optional idle mode handling

Will be addressed in a separate issue.

> probably, optional non-blocking I/O

Postponed.

> probably, ability to share single network loop for multiple objects

Done.

> probably, ability to embed roc event loop into the user application

Postponed.

> options to configure sender and receiver parameters, like payload type, FEC scheme, etc.

Done.

**Comment by gavv** [comment]
Most things were done in #80. IDLE handling will be addressed in #152 and #72. Session negotiation and control will be addressed in #34 and #204. Service discovery will be addressed later.

**Comment by selurvedu** [comment]
> Service discovery will be addressed later.

Hi @gavv, is this tracked anywhere? I found this issue to be the only one tham mentions service discovery.

**Comment by gavv** [comment]
@selurvedu Hi! What exactly are you looking for, support in C API? Or in pulseaudio/pipewire modules?

**Comment by selurvedu** [comment]
@gavv I'm looking for possible ways to implement something similar to:

https://docs.pipewire.org/page_module_raop_discover.html
https://docs.pipewire.org/page_module_zeroconf_discover.html
https://github.com/PipeWire/pipewire/blob/1.2/src/modules/module-snapcast-discover.c#L40 (no rendered docs page yet; available since PipeWire 1.2.0)

**Comment by gavv** [comment]
@selurvedu I see. We don't have this. It's actually on [roadmap](https://roc-streaming.org/toolkit/docs/development/roadmap.html) (see `Discovery API`). I was thinking about providing `roc_publisher` / `roc_explorer` API to abstract SAP/SDP and probably mDNS, but AFAIK it's not on anyone's to-do list for now.

You may find useful this tiny implementation of SAP listener: https://github.com/gavv/MiniSAPListener
