### ISSUE TITLE
Resampler quality

### ISSUE THREAD

**Issue by baranovmv** [roc-project/roc#153]
## What's wrong

While running roc-resample with bypassed resampler:
```
bool Resampler::resample_buff(Frame& out) {
    roc_panic_if(!prev_frame_);
    roc_panic_if(!curr_frame_);
    roc_panic_if(!next_frame_);

    static size_t window_i = 0;

    for (; out_frame_i_ < out.size(); out_frame_i_ += channels_num_) {
        if(window_i >= window_size_){
            window_i = 0;
            return false;
        }
        out.data()[out_frame_i_] = curr_frame_[window_i];
        out.data()[out_frame_i_+1] = curr_frame_[window_i+1];
        window_i += channels_num_;
    }
    out_frame_i_ = 0;
    return true;
}
```
so that the output of resampler is a copy of the input, the spectrum of the resulting wav-file looks like that:

![screenshot from 2018-02-05 13 29 56](https://user-images.githubusercontent.com/1952503/35800031-b8a80820-0a78-11e8-917d-ed1b8d69d596.png)

## How to reproduce

1. modify resampler.cpp with the snippet from above and compile,
2. generate sample signal with singen.py,
3. `bin/x86_64-pc-linux-gnu/roc-resample -i /tmp/sin.wav -o /tmp/sin_out.wav -r48000 --interp=2048 --window=128 --frame=2048`
4. compare input signal spectrum vs. output: `./double_spectrum.py -f /tmp/sin_out.wav -i /tmp/sin.wav`

**Comment by baranovmv** [comment]
* [singen.py](https://github.com/roc-project/roc/blob/kaiser/singen.py)
* [double_plot.py](https://github.com/roc-project/roc/blob/kaiser/double_spectrum.py)

**Comment by gavv** [comment]
It seems that you forget to cut the first and last 1024 samples (frame_size / channel_num) from the original signal. Resampler always cuts them so I guess we  should exclude them from the comparison. Also, SoX writer drops some samples at the end.

After taking this into account, I got the following results:

![spectrum](https://user-images.githubusercontent.com/8436629/50956776-97414880-14cd-11e9-842e-4bd889b342b2.png)

So it's not a leakage, it's how the original signal looks like. When the resampler is hacked to copy its input, the output is indeed identical to the input. When the resampler is functioning, the spectrum is changed, but there is no leakage, as I understand it.

I've also prepared a script that plots the difference between the input and output signals. Results:

![diff](https://user-images.githubusercontent.com/8436629/50956778-9a3c3900-14cd-11e9-9766-d56c355075bf.png)

My scripts: https://gist.github.com/gavv/56fa6c81eb26244e8d891da5293eaef8

Command to run resampler:

```
$ roc-conv -vv -i original.wav -o resampler_sc1.wav -r 48000 \
  --resampler-interp=2048 --resampler-window=128 --resampler-frame=2048
```

It is also possible now to disable resampler completely and just copy the signal using SoX:

```
$ roc-conv -vv -i original.wav -o resampler_sc1.wav -r 48000 \
  --no-resampling
```

The output is also identical to the input, as well as with the hacked resampler from your comment above.

**Comment by gavv** [comment]
Another thing that I noticed is that the resampler gains the signal a bit (just like the SoX resampler, for example).

**Comment by gavv** [comment]
One more sample.

Input signal:

<img src="https://user-images.githubusercontent.com/8436629/56922267-762e5300-6ad0-11e9-923d-2646fe71c6df.png" data-canonical-src="https://user-images.githubusercontent.com/8436629/56922267-762e5300-6ad0-11e9-923d-2646fe71c6df.png" width="300"/>

Zoomed input:

<img src="https://user-images.githubusercontent.com/8436629/56922372-b55ca400-6ad0-11e9-8f1d-6b81425f8c01.png" data-canonical-src="https://user-images.githubusercontent.com/8436629/56922372-b55ca400-6ad0-11e9-8f1d-6b81425f8c01.png" width="300"/>

Zoomed input vs output:

![image](https://user-images.githubusercontent.com/8436629/56922552-1be1c200-6ad1-11e9-96fa-5638059149db.png)

diff(input) vs diff(output):

![image](https://user-images.githubusercontent.com/8436629/56922706-898dee00-6ad1-11e9-86a2-3b989058bb53.png)

Zoomed diff(input) vs diff(output):

![image](https://user-images.githubusercontent.com/8436629/56922768-a9bdad00-6ad1-11e9-8bbc-92f07eec2b6c.png)

**Comment by gavv** [comment]
See also #105.
