### ISSUE TITLE
Improve self-profiling support

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#162]
We have `ProfilingWriter` pipeline element. It implements `IWriter` interfaces and itself acts as a proxy for another `IWriter`. During that proxying, it measure the average `write()` time (i.e. average frame processing time) and periodically reports it via `roc_log()`.

This element is currently used only in the `roc-conv` command-line tool, which uses `pipeline::Converter` pipeline.

We need a few improvements here:

* First, we need an improvement in `ProfilingWriter` itself: we should  use moving average instead of the overall average.

* Second, we should make it optional. Currently it is enabled in `pipeline::Converter` unconditionally. Instead, we should add `--profiling` command-line option and add `ProfilingWriter` to the pipeline only if that option was passed. An example of a conditionally-added pipeline element is `Interleaver` in `pipeline::Sender`.

* Finally, we should also add `ProfilingWriter` element to `pipeline::Sender` and `pipeline::Receiver` and add `--profiling` option to `roc-send` and `roc-recv` command-line tools.

Docs:

* https://roc-project.github.io/roc/docs/internals/code_structure.html
* https://roc-project.github.io/roc/docs/internals/data_flow.html

**Comment by RohanK99** [comment]
What is the moving average with respect to as in what is the rolling window that we want to calculate the average of? Is this based on the variable moving window that the resampler is operating on? If so how can we extrapolate that value for use to get the moving average for ProfileWriter::write

**Comment by gavv** [comment]
Hi! Sorry for late reply.

> Is this based on the variable moving window that the resampler is operating on?

Not quite. ProfilingWriter is the user of Resampler and itself is used by the sound I/O code. Sound I/O code reads (usually) fixed-size frames from ProfilingWriter, and it, in turn, reads these frames from Resampler. Resampler fills the requested fixed-size frames by reading a necessary amount of smaller-size frames from underlying pipeline components and scaling them a bit.

ProfilingWriter just calculates number of samples per second which goes through it. Actually it doesn't bother what the frame size is (variable, fixed, etc.)

Currently it calculates the average speed from the beginning of times, which is not very convenient. And I'm suggesting to replace it with SMA, i.e. calculate the average speed only for the last N samples (e.g. for last `5*sample_rate` samples, i.e. last 5 seconds).

**Comment by RohanK99** [comment]
Should the duration of the window in seconds (eg. 5 second window) be configurable as a command line option? or should I fix it as a constant somewhere and if so what should that constants value be?

**Comment by gavv** [comment]
I think for now we can hardcode it to 5 seconds.

**Comment by RohanK99** [comment]
How can we add `ProfilingWriter` to the `pipeline::Receiver` since it takes an `IWriter` as a constructor argument. We would need to create something like `ProfilingReader` in order to attain the desired outcome. Unless there is another way that I am overlooking on integrating `ProfilingWriter` with `pipeline::Receiver`

**Comment by gavv** [comment]
My bad, you're right. We need `ProfilingReader` for `pipeline::Receiver`.

We can extract `Profiler` class with methods like `begin_frame()` and `end_frame()`. This class will compute SMA and report it periodically. Then we can reuse it in `ProfilingReader` and `ProfilingWriter` (call `begin_frame` before reading/writing frame and `end_frame` after it). We already use the same approach with `Resampler`, `ResamplerReader`, and `ResamplerWriter`.

> Also on a side note, what version of C++ are we using should I be able to use constexpr?

https://roc-project.github.io/roc/docs/development/coding_guidelines.html

We use C++98, so we can't use constexpr.

> I think for now we can hardcode it to 5 seconds.

After some though, I think it's better to use the same value as (also hardcoded) report interval. Currently it's one second:

```
const core::nanoseconds_t LogInterval = core::Second;
```

Let's just use this constant both as report interval and SMA window length.

**Comment by RohanK99** [comment]
If I want to use `#include <deque>` in my code do I have to add that to "stddefs.h" and include that or would you prefer I just created a double ptr circular buffer?

**Comment by gavv** [comment]
@RohanK99 I've also added `pipeline::ConverterSource` to develop. We'll need to add `ProfilingReader` to it too.

**Comment by gavv** [comment]
Landed!
