### ISSUE TITLE
Configure internal frame size in nanoseconds

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#164]
All durations available via public API are now configured in nanoseconds instead of number of samples (packet length, latency, timeouts, etc.)

The only duration parameter that is still configured in number of samples is the `internal_frame_size` (it appears three times in `roc_pipeline/config.h`).

This is not critical since it's not visible in the public API for now. But it would be nice to configure it in nanoseconds too because:

* it will make this parameter independent of the sample rate and channel set
* this parameter affects latency and it is easier to understand the overall latency if all its components are calculated in the same encoding-independent units (nanoseconds in our case)
* this parameter may be added to public API later, and all such parameters in the API should be in nanoseconds

So what we need to do:

* Change type of `internal_frame_size` from `size_t` to `core::nanoseconds_t`.

* Find all components to which this parameter is passed from roc_pipeline. Add sample rate and channel mask parameters to constructors of all these components. Then, inside those constructors, calculate the actual number of samples using `timestamp_from_ns()` function, something like: `packet::timestamp_from_ns(internal_frame_size, sample_rate) * packet::num_channels(channels)`.

* In roc-recv, roc-send, and roc-conv command-line tools, use the string type for the `--frame-size` option and use `parse_duration()` function to parse this string into a nanoseconds value.

**Comment by hrishikeshSuresh** [comment]
If no one else is working on this, can I pick this issue?

**Comment by gavv** [comment]
Sure!

**Comment by gavv** [comment]
PR is merged. So we have finally finished migration from samples to nanoseconds, which is cool :) Thanks @hrishikeshSuresh!
