### ISSUE TITLE
FEC: validate source block length

### ISSUE THREAD

**Issue by dshil** [roc-project/roc#178]
## Issue

Due to #174 now it is possible to change the source block dynamically. As a
result, invalid value for the source block can be set and we will get an error
from the OpenFEC library because different schemes have different limits for
the maximum value of the source block size. ROC panics because of this error.

## Solution

**Writer**

If the size of a source block exceeds the limit of the selected scheme, 
writer should not update the size of source block.

**Reader**

If the size of a source block exceeds the limit of the selected scheme, 
the reader should ignore packets from this block.

For more info see:

* https://github.com/roc-project/roc/pull/174#discussion_r277381255
* https://www.freelists.org/post/roc/fec-writer-alive

**Comment by gavv** [comment]
We can add IEncoder::max_source_block() and IDecoder::max_source_block(), report them from OFEncoder and OFDecoder depending on the selected scheme and and check them in Writer and Reader.
