### ISSUE TITLE
Get rid of hardcoded resampler frame size?

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#18]
Resampler frame size is configured at compile time. Does it indirectly depend on other parameters, like packet size and player frame size?

If so, using non-default values for those parameters may break resampler.

**Comment by baranovmv** [comment]
No, it depends on chosen length of the sinc table in **sinc_table.h**. It won't be broken (only distort sound) if you decide to tune the impulse response length. But  it is obvious that you have to do so in accordance with available sinc table.

**Comment by gavv** [comment]
Ah, I see now. So what are the requirements for frame size? `NWindow < FrameSize < NWindow * 2`?

**Comment by baranovmv** [comment]
There are few checks in resampler like this:
```
roc_panic_if(Nwindow * scaling_ >= FrameSize);
```

`scaling_` is the frequency coefficient.

**Comment by gavv** [comment]
When you set `FrameSize` in config, it's not obvious that it also changes limit for minimum allowed scaling, depending on hidden `NWindow` parameter hardcoded inside resampler implementation. I don't like this.

I see two solutions here:
1. We could remove `FrameSize` from global config and make it internal parameter of resampler, just like `NWindow`.
2. We could replace `FrameSize` with `MinScaling` global parameter and define `FrameSize` as `NWindow * MinScaling`.

Which is better?

We also need to document these relations somewhere.

**Comment by baranovmv** [comment]
1. Changing `NWingow` and `FrameSize` makes sense if someone tries to tune resampler or just researching its quality. But for now we never even thought about that. So first option won't hurt anybody for some time.
2. Second one is wise decision but it requires some efforts to analyse how all this parameters depends on each other.

**Comment by gavv** [comment]
I finally ended with keeping resampler frame size in config, because it directly affects minimum required latency in server (see #44).

I believe we want to configure its actual value rather than playing with `MaxScaling` and `Nwindow`, since it's important for us to have straightforward parameters that affect latency.

**Comment by gavv** [comment]
Resampler frame size is now documented and configurable at runtime.

There is really distort sound on higher values starting from ~200. Could we document preferred value range that doesn't hurt sound quality?

**Comment by baranovmv** [comment]
Values of what? The size of frame?

**Comment by gavv** [comment]
Yes, resampler frame size.

**Comment by baranovmv** [comment]
Resampler frame size value must not produce influence on sound quality anyhow. It seems like bug, I'll check it.

**Comment by gavv** [comment]
### How to reproduce

#### Client

    bin/roc-send -vv -i song.flac 127.0.0.1:12345

#### Server

Good:

    bin/roc-recv -vv :12345 -1 --resampler-frame 192

Bad:

    bin/roc-recv -vv :12345 -1 --resampler-frame 200

Even worse:

    bin/roc-recv -vv :12345 -1 --resampler-frame 250

Note that `192 % 64 == 0` but `200 % 64 != 0` and `250 % 64 != 0`.

**Comment by gavv** [comment]
Note that it's not possible to set `resampler_frame >= 256`:

    PANIC: roc_audio: !(qt_frame_size_ >= G_qt_half_window_len)

**Comment by gavv** [comment]
BTW, maybe it makes sense to implement #19 before debugging resampler.

**Comment by baranovmv** [comment]
In this particular case I hope we'll manage without any special tooling. But python and matlab are very useful anyway :+1:

**Comment by baranovmv** [comment]
This is what we hear as distortion on "wrong" resamplers frame size.
![sin_distortion2](https://cloud.githubusercontent.com/assets/1952503/12350345/8ad54d28-bb87-11e5-8c8e-99f0d3ac942a.jpg)
![sin_distortion](https://cloud.githubusercontent.com/assets/1952503/12350344/8ad1e976-bb87-11e5-813a-e30d383f0729.jpg)

This particular example I've collect with frame size of 200.

Length of the gap is 7 or 8 samples. I don't know yet if it depends on frame size or not.

**Comment by baranovmv** [comment]
* If we fix frequency coefficient to 1, it won't glitch at all.
* If we set size of resamplers frame to value under 128 (for example 100), it won't glitch too.

**Comment by gavv** [comment]
Probably related to fixed-point precision? Maybe it makes sense to check if it's still reproducible with 64-bit fixed points.

**Comment by baranovmv** [comment]
Looks like the issue relates somehow to 8bit length of integral part of
fixed point type.

пт, 15 Янв 2016, 17:53, Victor Gaydov <notifications@github.com>:

**Comment by gavv** [comment]
> Looks like the issue relates somehow to 8bit length of integral part of fixed point type.

Then, I think [this problem](https://github.com/roc-project/roc/issues/18#issuecomment-169677336) (mentioned above) is the same issue.

**Comment by baranovmv** [comment]
It's hard to explain in comment what was the cause of bug. I'll write an article about resamplers guts later.
The main reason was that the resampler considered its impulse response windows half length of 63 and 63/64 (equal to 64-1/64). Don't ask me why. Changing this value to 64 make us to run into other flaws.
I've fixed every issue and it seems working correctly now.
You may set any value of frame size in range from 65 to 191 now. 65 is bigger than half of window size. 191 is smaller than 256-half window size.

**Comment by gavv** [comment]
Great!

> You may set any value of frame size in range from 65 to 191 now. 65 is bigger than half of window size. 191 is smaller than 256-half window size.

I guess this is a check for that?

```
    // Half window must fit into one frame.
    roc_panic_if_not(qt_frame_size_ >= G_qt_half_window_len);

    // Check if frame_size_ fits to fixedpoint type.
    roc_panic_if( (uint64_t)qt_frame_size_ + (uint64_t)G_qt_half_window_len >= (INTEGER_PART_MASK + FRACT_PART_MASK) );
```

I think it would better to use `roc_panic()` instead of `roc_panic_if()` here to print meaningful error for user, something like "scaling value is too low; allowed values should be in range ...".

**Comment by baranovmv** [comment]
> I think it would better to use roc_panic() instead of roc_panic_if() here to print meaningful error for user, something like "scaling value is too low; allowed values should be in range ...".
Done in 9bcab57e63eb986c6c7e6c20c63c3482ee250322
