### ISSUE TITLE
Pulseaudio module compilation issue with glibc >= 2.27

### ISSUE THREAD

**Issue by P-D-G** [roc-project/roc#190]
Hi

I've been having difficulties compiling the pulseaudio module on Linux Mint (Ubuntu 18.04 base). The problem happens when making pulseaudio 11.1. The command I use is:

`scons -Q --enable-pulseaudio-modules --build-3rdparty=openfec,pulseaudio`

The error message is as follows:

`In file included from pulsecore/shm.c:48:0:
./pulsecore/memfd-wrappers.h:36:19: error: static declaration of ‘memfd_create’ follows non-static declaration
 static inline int memfd_create(const char *name, unsigned int flags) {
                   ^~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:115:0,
                 from /usr/include/x86_64-linux-gnu/bits/mman.h:45,
                 from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
                 from pulsecore/shm.c:37:
/usr/include/x86_64-linux-gnu/bits/mman-shared.h:46:5: note: previous declaration of ‘memfd_create’ was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~`

The problem is apparently known (https://bugs.freedesktop.org/show_bug.cgi?id=104733) and a patch exists for package maintainers (https://bugs.freedesktop.org/attachment.cgi?id=136927). I can compile pulseaudio 11.1 with this patch, however scons re-downloads a fresh archive and erase the patch, thus failing again. 

It does not happen if I force a more recent pulseaudio version (ex: --build-3rdparty=openfec,pulseaudio:12.0). I can get the module compiled but can't run it with pulseaudio 11.1.

Is there a way to automagically apply the patch in the scons build process ? 

Thanks for your help, I can get more info if needed.

**Comment by gavv** [comment]
Hi!

There is no way to make scons to apply custom patches right now.

The recommended way to deal with such situations is to build pulseaudio manually (with the patch applied) outside the roc directory and then use `--with-pulseaudio` scons option, like:

```
scons -Q --enable-pulseaudio-modules --build-3rdparty=openfec \
  --with-pulseaudio=/path/to/pulseaudio/source/dir
```

Unfortunately it seems that this option was broken for a while :/

I've fixed it and pushed the fix to develop and master.

Another approach is to fix scons so it would not remove third-party source directories if they were successfully extracted earlier. It's not possible now, but sounds reasonable. I'll fix that as well.

**Comment by gavv** [comment]
> Another approach is to fix scons so it would not remove third-party source directories if they were successfully extracted earlier. It's not possible now, but sounds reasonable. I'll fix that as well.

Done and pushed to develop and master.

Now you should be able to patch the extracted pulseaudio sources and run scons again. The second invocation should print something like:

```
[found cached] pulseaudio-11.1.tar.gz
[found cached] pulseaudio-11.1
```

(However note that "scons clean" will remove 3rdparty directories anyway so the "--with-pulseaudio" method is still preferred).

**Comment by P-D-G** [comment]
Hi,

I just tested, it compiles OK with the patch. 

For future reference, the compilation steps to bypass this problem are:

1. compile with the "--with-pulseaudio" option (will fail, this is normal)
2. apply this patch (https://bugs.freedesktop.org/attachment.cgi?id=136927) in 3rdparty repository
3. compile with the "--with-pulseaudio" option again

For my part this solves the bug, since its primarily dependant on pulseaudio and glibc versions, so I'll close it.

Thanks for the quick workaround :)

**Comment by gavv** [comment]
Roc will now automatically download and apply this patch when building PulseAudio (if its version is between 8.99.1 and 11.99.1). This is merged into the master branch.
