### ISSUE TITLE
Can't stream from file using bare RTP

### ISSUE THREAD

**Issue by dshil** [roc-project/roc#219]
How to reproduce:

```sh
scons -Q --disable-openfec --build-3rdparty=cpputest
roc-send -s rtp:127.0.0.1:10001 -i foo.wav
roc-recv -s rtp:127.0.0.1:10001
```

**Comment by gavv** [comment]
Are any tests failing? If not, we should add a pipeline-level test that will catch this. We should also add a build without OpenFEC to CI.

**Comment by gavv** [comment]
I can't reproduce this. The commands above work for me. @dshil could you re-check it on fresh develop?

**Comment by gavv** [comment]
Oops, I was able to reproduce it. But it's not a bug, it's the same problem as described here https://github.com/roc-project/roc/issues/220#issuecomment-506498907
