### ISSUE TITLE
Validate that FEC scheme is consistent with ports

### ISSUE THREAD

**Issue by dshil** [roc-project/roc#221]
We should not allow user of `roc-recv`, `roc-send` to mix the coding schemes:

```sh
roc-recv -vv -s rtp+ldpc::10001 -r rs8m::10002
roc-send -vv -s rtp+rs8m:127.0.0.1:10001 -r ldpc:127.0.0.1:10002
```

* sender should use the same coding scheme for source and repair ports
* receiver should use the same coding scheme for source and repair ports
* If the receiver uses RS (Reed-Solomon) coding scheme, the receiver should
  use the same coding scheme, otherwise, the behaviour is undefined (the same
  is true for any coding scheme). It will be handled when the receiver will be able to
  communicate with the sender via SDP.

**Comment by gavv** [comment]
We probably want to perform validation in roc_pipeline to make it work both for tools and API.

**Comment by gavv** [comment]
Note that this invocation:

```
roc-recv -vv -s rtp+ldpc::10001 -r rs8m::10002
```

is perfectly OK by itself. You can start receiver with any set of ports of any type, e.g. this will be also okay:

```
roc-recv -vv -s rtp+ldpc::10001 -r rs8m::10002 -s rtp+rs8m::10003 -r ldpc::10004 
```

The receiver has no global FEC scheme. Instead, every session on the receiver has its own FEC scheme.

So what you need to validate here is that all packets routed to a session have the same FEC scheme as that session. You can do it by checking `packet.fec().fec_scheme` field which is set accordingly to the protocol of the receiver port that handled the packet.

I think the best place to do it is fec::Reader.

As for the sender, it *has* global FEC scheme, and this invocation:

```
roc-send -vv -s rtp+rs8m:127.0.0.1:10001 -r ldpc:127.0.0.1:10002
```

is equal to:

```
roc-send -vv -s rtp+rs8m:127.0.0.1:10001 -r ldpc:127.0.0.1:10002 --fec=rs8m
```

We can perform the validation in fec::Writer and similarly check that the output packets have the same scheme as the writer itself.

We could also perform some early validation when we are creating pipeline.

**Comment by gavv** [comment]
To summarize, we should check that:

* protocols of sender ports correspond to sender fec scheme

and:

* fec::Writer and fec::Composer use the same FEC scheme
* fec::Reader and fec::Parser use the same FEC scheme

In addition, we should produce meaningful error messages when:

* fec scheme is not none, but repair port is not present
* fec scheme is none, but repair port is present

**Comment by gavv** [comment]
It would also be nice to get rid of ROC_TARGET_OPENFEC #ifdefs by introducing a factory for FEC codecs, just like we already have for audio codecs.

**Comment by gavv** [comment]
Done.
