### ISSUE TITLE
Add more roc_fec tests

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#23]
Implement tests currently marked as `IGNORE_TEST` and `TODO`.

**Comment by baranovmv** [comment]
Finished all planned tests

**Comment by gavv** [comment]
We'll also need `encode_source_id`, but it's not in `develop` branch yet. I'll merge it soon.

**Comment by gavv** [comment]
Merged into `develop`: [`IGNORE_TEST(fec_codec_integration, encode_source_id)`](https://github.com/roc-project/roc/blob/develop/src/tests/roc_fec/target_openfec/test_codec_integration.cpp#L441).

**Comment by baranovmv** [comment]
The name `encode_source_id` doesn't give much. What should we check in the test?

**Comment by gavv** [comment]
`audio::Splitter` and `fec::Encoder` now set `SSRC` field for every generated packet, see 1addccfc0e42bd7300dcbce5e76799587e00be8a (auto-linked above).

`SSRC` is the same for all generated packets and is set to random-value in constructor.

**Comment by gavv** [comment]
Do we also have tests for:
* decoding more than once time per block

  when `try_repair_()` is called multiple times for a single block, e.g. when decoder receives new *FEC* packets and still have lost data packets

* delayed packet

  when decoder returns NULL instead of packet `#N` (because packet `#N` can't be repaired and there is no more packets in block and input queue), and then it receives packet `#N` and returns it

* dropped packet

  when decoder skips packet `#N` and returns packet `#N+1` (because it can't be repaired and next packet is available), and then, when packet `#N` is received, it is dropped

**Comment by gavv** [comment]
I've added `encode_source_id` test, see 19222e944c6e12b9dac7a2e6a2d592514bca4f8e.

**Comment by baranovmv** [comment]
> decoding more than once time per block

That's good test, I'll do it. It'll be inconvenient to implement this in `fec_codec_integration` environment. So I'll do `fec_codec_unittests`

> delayed packet

Its just shame that I missed this.

> dropped packet

I'll add this to `decoding_late_packet`

**Comment by gavv** [comment]
It seems that we're done.
