### ISSUE TITLE
JNI bindings

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#233]
Create bindings to the public API for Java/Kotlin. This, among other things, will allow us to create native Android apps based on Roc, which would be very nice.

The API can be found in `src/lib/include`. The bindings should be likely placed in a separate repo in the roc-project organization.

Likely, the JNI bindings should provide a higher-level wrappers on top of the C library, just like Go bindings. See discussion here: #248, #269.

We should also add some unit-tests for the JNI bindings (likely written in Java). We will add them to our continuous integration.

These resources can be useful: [1](https://developer.android.com/training/articles/perf-jni), [2](https://stackoverflow.com/questions/18334547/how-to-use-the-same-c-code-for-android-and-ios/18334548).

**Comment by dwlsalmeida** [comment]
Hey there!

I am willing to take this IF there is help.
What do you say @gavv ?

https://medium.com/@bschlining/a-simple-java-native-interface-jni-example-in-java-and-scala-68fdafe76f5f
This seems rather straightforward. Is this what you guys are looking for?

**Comment by gavv** [comment]
Great, you're welcome!

> This seems rather straightforward. Is this what you guys are looking for?

Yes.

If you're starting working on this, I can create a new repo in our github org, say, roc-project/roc-java, just like we have [one](https://github.com/roc-project/roc-go) for Go bindings.

**Comment by dwlsalmeida** [comment]
@gavv 

Cool man, please assign then.

**Comment by gavv** [comment]
https://github.com/roc-project/roc-java

**Comment by gavv** [comment]
@dwlsalmeida Hi, how is it going? Do you still have plans to work on this?

**Comment by dwlsalmeida** [comment]
Hi @gavv

Sorry, I know it is uncourteous to show up and then be gone but life briefly got in the way. Yes I still plan to work on this. Are you guys in a hurry?

**Comment by gavv** [comment]
No worries. Just pinging in case you've lost interest so that someone else could pick this up.

**Comment by dwlsalmeida** [comment]
@gavv https://github.com/roc-project/roc-java/pull/1

**Comment by gavv** [comment]
https://github.com/roc-project/roc-java/pull/2

**Comment by MatteoArella** [comment]
I'm actually working on this issue

**Comment by gavv** [comment]
The first version of java bindings is merged.
