### ISSUE TITLE
Add support for musl libc

### ISSUE THREAD

**Issue by leonlag** [roc-project/roc#239]
Currently it's assumed that glibc is installed when the target is linux. This is not always the case. 
A distro like alpine, which makes a lot of sense for devices like the rpi 0, ships with musl by default.

```
$ gcc -v -E 2>&1| grep Target:
Target: armv6-alpine-linux-musleabihf
```

**Comment by gavv** [comment]
Thanks for reporting. We have very few glibc-specific code so it would be easy to do this. We also should add non-glibc builds to CI. I think we'll do this in 0.1.2.

**Comment by gavv** [comment]
Fixed in develop branch. Added Alpine Linux to travis. Closing this, feel free to reopen if necessary.
