### ISSUE TITLE
build fails on ubuntu 18.04.03

### ISSUE THREAD

**Issue by muralikodali** [roc-project/roc#243]
build fails with following error :
[execute] make -j
scons: *** Error 1
error: can't make 'pulseaudio-11.1', see '3rdparty/x86_64-pc-linux-gnu/gcc-7.4.0-release/build/pulseaudio-11.1/build.log' for details

log file is attached for reference.
[build.log](https://github.com/roc-project/roc/files/3509411/build.log)

**Comment by gavv** [comment]
Hi,

I think you have discovered the problem described in #190: pulseaudio 11.1 fails to build with recent glibc versions without a patch.

You can resolve this one of the three ways:

* upgrade pulseaudio with your package manager (if it is possible)

* OR, download pulseaudio 11.1, extract it into a separate directory, download and apply the [patch](https://bugs.freedesktop.org/attachment.cgi?id=136927) linked in the issue above, build pulseaudio, and then build roc with the external pulseaudio directory (add `--with-pulseaudio=/path/to/pa/dir` option and remove `pulseaudio` from `--build-3rdparty` option)

* OR, apply the [patch](https://bugs.freedesktop.org/attachment.cgi?id=136927) directly to the `3rdparty/x86_64-pc-linux-gnu/gcc-7.4.0-release/build/pulseaudio-11.1/src/pulseaudio-11.1` directory; this approach is simpler but note that this directory will be removed if you will run `scons -c` or `scons clean`

    For example:

    ```
    cd 3rdparty/x86_64-pc-linux-gnu/gcc-7.4.0-release/build/pulseaudio-11.1/src/pulseaudio-11.1
    curl -s https://bugs.freedesktop.org/attachment.cgi?id=136927 > 1.patch
    patch -p1 < 1.patch
    ```

**Comment by muralikodali** [comment]
thanks for your guidance.
I have upgraded pulseaudio with ppa . 
compilation done without error. 
roc working now.

**Comment by gavv** [comment]
Roc will now automatically download and apply this patch when building PulseAudio (if its version is between 8.99.1 and 11.99.1).
