### ISSUE TITLE
Golang bindings

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#248]
Create Go bindings for libroc (our public C API).

The bindings should fit well into the Go type system: e.g. an audio frame is a raw pointer in the C API, but it likely should be a []byte slice in Go bindings.

I think it makes sense to provide a set of conventional wrappers for slices of different types, instead of a single method, e.g.:

```
func (s *Sender) WriteAudioBytes(data []byte) int
func (s *Sender) WriteAudioFloats(data []float) int
```

The bindings can be created manually using cgo or maybe we can partially generate the low-level private part using some bindings generator and then writer high-level public part on top of it manually.

We should also add some unit-tests for the Go bindings (written in Go). We will add them to our continuous integration.

The API can be found in `src/lib/include`. The bindings should be placed in `src/bindings/go` or something like this.

**Comment by Asalle** [comment]
In the name of hacktoberfest I am willing to solve this problem!

**Comment by gavv** [comment]
The first version of Go bindings is merged: https://github.com/roc-project/roc-go/pull/1

The remaining issues are tracked here: https://github.com/roc-project/roc-go/issues
