### ISSUE TITLE
problem building pulse modules on fedora 30

### ISSUE THREAD

**Issue by jave** [roc-project/roc#250]
error: can't make 'pulseaudio-12.2', see '3rdparty/x86_64-pc-linux-gnu/clang-8.0.0-release/build/pulseaudio-12.2/build.log' for details                                                                                                       

log mentions missing asoundlib.h. I do have this file on the system though.

**Comment by gavv** [comment]
Hi!

Do you have `alsa-lib-devel` installed? If not, you can try installing it.

If it doesn't help:

* Could you post the output of `pkg-config --cflags alsa` ?

* Could you attach the full `3rdparty/x86_64-pc-linux-gnu/clang-8.0.0-release/build/pulseaudio-12.2/build.log` and `config.log` files?

**Comment by gavv** [comment]
> log mentions missing asoundlib.h. I do have this file on the system though.

Where is it located?

**Comment by jave** [comment]
/usr/include/alsa/asoundlib.h                                                                                                                                                                                                                 
/usr/include/sys/asoundlib.h

**Comment by jave** [comment]
rpm -qa|grep alsa                                                                                                                                                                                            
alsa-lib-devel-1.1.9-1.fc30.x86_64                                                                                                                                                                                                            
alsa-plugins-pulseaudio-1.1.9-1.fc30.x86_64                                                                                                                                                                                                   
alsa-utils-1.1.9-1.fc30.x86_64                                                                                                                                                                                                                
alsa-lib-1.1.9-1.fc30.x86_64                                                                                                                                                                                                                  
alsa-ucm-1.1.9-1.fc30.noarch                                                                                                                                                                                                                  
qemu-audio-alsa-3.1.1-2.fc30.x86_64

**Comment by jave** [comment]
pkg-config --cflags alsa 

output is empty. This feels a bit odd.

**Comment by gavv** [comment]
Ok, what is the output of:

    pkg-config --print-errors --cflags alsa

and

    pkg-config --debug --validate alsa

Do you have `alsa.pc` somewhere on the system? If yes, what is its contents?

**Comment by gavv** [comment]
Also, what is the exact command you're using to build Roc?

**Comment by jave** [comment]
pkg-config --print-errors --cflags alsa                                                                                                                                                                      
                                                                                                                                                                                                                                              
[joakim@tanaka pulseaudio-12.2]$ pkg-config --debug --validate alsa                                                                                                                                                                           
                                                                                                                                                                                                                                              
libpkgconf/dependency.c:115 [add_or_replace_dependency_node]: added dependency [alsa] to list @0x7ffcd043a1f8; flags=0                                                                                                                        
libpkgconf/pkg.c:1495 [pkgconf_pkg_traverse]: virtual:world: level 2000                                                                                                                                                                       
libpkgconf/pkg.c:1510 [pkgconf_pkg_traverse]: virtual:world: walking requires list                                                                                                                                                            
libpkgconf/pkg.c:1276 [pkgconf_pkg_verify_dependency]: trying to verify dependency: alsa                                                                                                                                                      
libpkgconf/pkg.c:663 [pkgconf_pkg_find]: looking for: alsa                                                                                                                                                                                    
libpkgconf/cache.c:62 [pkgconf_cache_lookup]: miss: alsa                                                                                                                                                                                      
libpkgconf/pkg.c:502 [pkgconf_pkg_try_specific_path]: trying path: /usr/lib64/pkgconfig for alsa                                                                                                                                              
libpkgconf/pkg.c:515 [pkgconf_pkg_try_specific_path]: found: /usr/lib64/pkgconfig/alsa.pc                                                                                                                                                     
libpkgconf/tuple.c:189 [pkgconf_tuple_add]: adding tuple to @0x565355c01f08: pcfiledir => /usr/lib64/pkgconfig (parsed? 1)                                                                                                                    
libpkgconf/tuple.c:189 [pkgconf_tuple_add]: adding tuple to @0x565355c01f08: prefix => /usr (parsed? 1)                                                                                                                                       
libpkgconf/tuple.c:189 [pkgconf_tuple_add]: adding tuple to @0x565355c01f08: exec_prefix => /usr (parsed? 1)                                                                                                                                  
libpkgconf/tuple.c:189 [pkgconf_tuple_add]: adding tuple to @0x565355c01f08: libdir => /usr/lib64 (parsed? 1)                                                                                                                                 
libpkgconf/tuple.c:189 [pkgconf_tuple_add]: adding tuple to @0x565355c01f08: includedir => /usr/include (parsed? 1)                                                                                                                           
libpkgconf/fragment.c:669 [pkgconf_fragment_parse]: post-subst: [-L${libdir} -lasound] -> [-L/usr/lib64 -lasound]                                                                                                                             
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {L, '/usr/lib64'} to list @0x565355c01e48                                                                                                                                    
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {l, 'asound'} to list @0x565355c01e48                                                                                                                                        
libpkgconf/fragment.c:669 [pkgconf_fragment_parse]: post-subst: [-lm -ldl -lpthread -lrt] -> [-lm -ldl -lpthread -lrt]                                                                                                                        
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {l, 'm'} to list @0x565355c01e60                                                                                                                                             
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {l, 'dl'} to list @0x565355c01e60                                                                                                                                            
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {l, 'pthread'} to list @0x565355c01e60                                                                                                                                       
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {l, 'rt'} to list @0x565355c01e60                                                                                                                                            
libpkgconf/fragment.c:669 [pkgconf_fragment_parse]: post-subst: [-I${includedir}] -> [-I/usr/include]                                                                                                                                         
libpkgconf/fragment.c:147 [pkgconf_fragment_add]: added fragment {I, '/usr/include'} to list @0x565355c01e78                                                                                                                                  
libpkgconf/dependency.c:115 [add_or_replace_dependency_node]: added dependency [alsa = 1.1.9] to list @0x565355c01ef0; flags=0                                                                                                                
libpkgconf/pkg.c:465 [pkgconf_pkg_ref]: refcount@0x565355c01df0: 1                                                                                                                                                                            
libpkgconf/pkg.c:465 [pkgconf_pkg_ref]: refcount@0x565355c01df0: 2                                                                                                                                                                            
libpkgconf/cache.c:87 [pkgconf_cache_add]: added @0x565355c01df0 to cache                                                                                                                                                                     
libpkgconf/pkg.c:465 [pkgconf_pkg_ref]: refcount@0x565355c01df0: 3                                                                                                                                                                            
libpkgconf/pkg.c:1495 [pkgconf_pkg_traverse]: alsa: level 1999                                                                                                                                                                                
libpkgconf/pkg.c:1510 [pkgconf_pkg_traverse]: alsa: walking requires list                                                                                                                                                                     
libpkgconf/pkg.c:488 [pkgconf_pkg_unref]: refcount@0x565355c01df0: 2                                                                                                                                                                          
libpkgconf/pkg.c:488 [pkgconf_pkg_unref]: refcount@0x565355c01df0: 1

**Comment by jave** [comment]
scons -Q --enable-pulseaudio-modules --build-3rdparty=openfec,pulseaudio,cpputest

**Comment by jave** [comment]
cat /usr/lib64/pkgconfig/alsa.pc                                                                                                                                                                             
prefix=/usr                                                                                                                                                                                                                                   
exec_prefix=/usr                                                                                                                                                                                                                              
libdir=/usr/lib64                                                                                                                                                                                                                             
includedir=/usr/include                                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
Name: alsa                                                                                                                                                                                                                                    
Description: Advanced Linux Sound Architecture (ALSA) - Library                                                                                                                                                                               
Version: 1.1.9                                                                                                                                                                                                                                
Requires:                                                                                                                                                                                                                                     
Libs: -L${libdir} -lasound                                                                                                                                                                                                                    
Libs.private: -lm -ldl -lpthread -lrt                                                                                                                                                                                                         
Cflags: -I${includedir}

**Comment by jave** [comment]
[build.log](https://github.com/roc-project/roc/files/3596110/build.log)
[config.log](https://github.com/roc-project/roc/files/3596112/config.log)

**Comment by gavv** [comment]
Thanks. Now it became clear.

Here is a similar bug: https://bugzilla.redhat.com/show_bug.cgi?id=1716389

ALSA upstream has [changed](https://alsa-project.org/wiki/Changes_v1.1.8_v1.1.9) its `alsa.pc` file so that now its includedir is `/usr/include`, not `/usr/include/alsa`, and programs using ALSA should now include `alsa/asoundlib.h`, not `asoundlib.h`. 

PulseAudio 12.2 still uses `asoundlib.h` and so wont build with recent ALSA. PulseAudio 12.99.1 and leter uses `alsa/asoundlib.h` and so it should work.

As a workaround, you can try something like:

```
cd 3rdparty/x86_64-pc-linux-gnu/clang-8.0.0-release/build/pulseaudio-12.2/src/pulseaudio-12.2
find -name '*.c' -or -name '*.h' | xargs sed -i 's|#include <asoundlib.h>|#include <alsa/asoundlib.h>|'
```

and then run scons again.

I'll update our build script to apply this patch automatically when building PulseAudio.

**Comment by gavv** [comment]
Done. Roc now automatically fixes includes when building PulseAudio.

@jave could you please check out fresh `develop` branch, run "scons clean", and then build Roc again and ensure that the problem is fixed?

**Comment by jave** [comment]
It builds now. Thanks!

**Comment by gavv** [comment]
You're welcome!
