### ISSUE TITLE
Add 3rdparty versions into version info

### ISSUE THREAD

**Issue by dshil** [roc-project/roc#256]
Recently we've [added a git](https://github.com/roc-project/roc/issues/241) sha to the version output (`roc-recv --version`).

Now, I think it would be reasonable to add some human readable info about our dependencies and probably their commit sha. I am not sure that it is suitable for the existing `--version` flag. Probably we could introduce something similar to `--info` with some easy to parse output.

`roc-recv --info`

```json
{
   "version": {
      "sha": "0xdeadbeaf" ,
      "build_user": "foo"
   },
   "deps": {
      "libuv": {
          "version": "1.5.0",
          "sha": 123,
          "upstream": "https://our.fork.com"
       },
       "sox": {
       },
       "fec": {
       }
   }
}
```

**Comment by dshil** [comment]
@gavv, first, I want to open an issue in libuv and their github template asked me to point to the build version. I did not find a quick way to find 3rdparty versions with which roc was build.

**Comment by gavv** [comment]
On one hand, producing some meta-information may be useful. For example, it would be nice to print the list of target directories enabled during build, the build command, and the compiler version. List of dependencies and their versions likely would be useful too.

On the other hand, Roc doesn't know and can't determine versions of the system libraries it uses. At least there is no generic way to do it. Some libraries provide corresponding defines in their headers, but some not, and BTW some of them are not accurate. We only known the exact version when we're using --build-3rdparty for the library, but this is not the default; using system libraries is preferred when possible.

So I think in most cases we just don't have enough information to produce the suggested output.

Also, I don't see any reason to use JSON here, which is intended to be used by programs. I'd prefer a simple plain-text format that is easier to read but still can be parsed if necessary.

**Comment by gavv** [comment]
> @gavv, first, I want to open an issue in libuv and their github template asked me to point to the build version. I did not find a quick way to find 3rdparty versions with which roc was build.

The quick way is to ask your package manager if you're using system libuv or to check the output of `ls -l 3rdparty/*/*/build` if you're using --build-3rdparty.

**Comment by gavv** [comment]
And if you need git sha, you can't get it. We download versioned tarballs and we don't known how these tarballs are related to the upstream repo.

BTW default versions for --build-3rdparty are listed here: https://github.com/roc-project/roc/blob/master/SConstruct#L27-L38

**Comment by dshil** [comment]
> On one hand, producing some meta-information may be useful. For example, it would be nice to print the list of target directories enabled during build, the build command, and the compiler version. List of dependencies and their versions likely would be useful too.
> 
> On the other hand, Roc doesn't know and can't determine versions of the system libraries it uses. At least there is no generic way to do it. Some libraries provide corresponding defines in their headers, but some not, and BTW some of them are not accurate. We only known the exact version when we're using --build-3rdparty for the library, but this is not the default; using system libraries is preferred when possible.
> 
> So I think in most cases we just don't have enough information to produce the suggested output.
> 
> Also, I don't see any reason to use JSON here, which is intended to be used by programs. I'd prefer a simple plain-text format that is easier to read but still can be parsed if necessary.

OK. I got your point. Probably, I will be OK with the output of `ls -l 3rdparty/*/*/build`.
