### ISSUE TITLE
Check dependencies before bulding 3rdparties in SCons

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#26]

**Comment by adrianopol** [comment]
Approve.

$ rm -rf bin/* build/* 3rdparty/ .scon*
$ scons --with-3rdparty=openfec test
scons: Reading SConscript files ...
Checking for C library uv... yes
Checking for C library sox... yes
Checking for executable gengetopt... (cached) no
error: gengetopt not found in PATH (looked for `gengetopt')

**Comment by gavv** [comment]
Good.
