### ISSUE TITLE
Document FreqEstimator and Resampler

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#27]
Please :)

https://github.com/roc-project/roc/wiki

**Comment by gavv** [comment]
https://github.com/roc-project/roc/wiki

**Comment by baranovmv** [comment]
The beginning: https://github.com/roc-project/roc/wiki/Resampling

**Comment by gavv** [comment]
:+1:

**Comment by gavv** [comment]
Moved to sphinx and improved: https://roc-project.github.io/docs/internals/fe_resampler.html
