### ISSUE TITLE
Generate and install pkg-config file

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#271]
`scons install` should generate and install a `libroc.pc` file for pkg-config.

The file contents should be something like:

```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=${prefix}/include

Name: libroc
Requires: libuv libunwind
Version: 0.1.3
Description: Real-time audio streaming over the network.
URL: https://roc-project.github.io

Libs: -L${libdir} -lroc -lrt -lpthread -lnsl -ldl -lm
Cflags: -I${includedir}
```

But paths (`/usr`, `/usr/lib64`), version (`0.1.3`), and dependencies (`libuv libunwind`) should be generated dynamically according to the .version file, installation prefix, and enabled dependencies. All this info is already available inside scons.

The file itself should be installed accordingly to the installation prefix and pkg-config default path. On my system it is `/usr/lib64/pkgconfig`.

The generation function should be added somewhere under `site_scons/site_tools/roc`. This is our scons plugin which provided various helpers.

This task is needed for our Go bindings: https://github.com/roc-project/roc-go/issues/4

**Comment by fusuiyi123** [comment]
if I understand correctly, we need to create a `libroc.pc` file in `PKG_CONFIG_PATH` and `prefix`, `libdir` `requires` are from scons options `--prefix=PREFIX`, `--libdir=LIBDIR`, not sure where do we get enabled dependencies, is it  https://github.com/roc-project/roc/blob/master/SConstruct#L732 ? Thanks!

**Comment by fusuiyi123** [comment]
and it's just writing a file to a path like `/usr/lib64/pkgconfig` not `AddDistFile` which is installing a target library..?

**Comment by gavv** [comment]
> if I understand correctly, we need to create a libroc.pc file in PKG_CONFIG_PATH and prefix, libdir requires are from scons options --prefix=PREFIX, --libdir=LIBDIR

Yes.

> not sure where do we get enabled dependencies, is it https://github.com/roc-project/roc/blob/master/SConstruct#L732 ?

Yes. We should add dependencies which are:

* listed in system_dependencies
* added to `env` using `ParsePkgConfig` (which also defined the pkg-config dependency name)
* are dependencies of libroc, not just tools or pulseaudio modules

> and it's just writing a file to a path like /usr/lib64/pkgconfig not AddDistFile which is installing a target library..?

I think we should add an AlwaysBuild action that generates libroc.pc file somewhere in the `build` directory and then add this file to the `install` target using AddDistFile()

**Comment by fusuiyi123** [comment]
thank you, I sent a pr #347

**Comment by gavv** [comment]
Merged.
