### ISSUE TITLE
Write or generate man pages for tools

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#28]
We could use `help2man` to generate man pages from `--help`.

**Comment by baranovmv** [comment]
As docs is being written in rest, sphinx could make man pages from it for granted. I've stolen descriptions of **roc-recv** and **roc-send** from those help and now `sphinx-build -b man . ../build` makes two man-pages in the doc branch.

**Comment by gavv** [comment]
I'm not sure that maintaining two copies of this text (in the source code and in the rst) is a good idea.
