### ISSUE TITLE
roc_lib test pure virtual method called

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#285]
Caught in #283.

Mangled:

```
#1: 0x50a187e _ZN3roc4core25print_emergency_backtraceEv+0x17
#2: 0x50a081c _ZN3roc4core12_GLOBAL__N_114signal_handlerEiP9siginfo_tPv+0x58
#3: 0x5ef2f20 killpg+0x40
#4: 0x5ef2e97 gsignal+0xc7
#5: 0x5ef4801 abort+0x141
#6: 0x55b785e __cxa_throw_bad_array_new_length+0x4c7
#7: 0x55c34f6 _ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE+0x76
#8: 0x55c3541 _ZSt9terminatev+0x11
#9: 0x55c426f __cxa_pure_virtual+0x1f
#10: 0x12c33d _ZN3roc12_GLOBAL__N_15Proxy12send_packet_ERNS_6packet7IReaderEb+0x43
#11: 0x12c2bd _ZN3roc12_GLOBAL__N_15Proxy5writeERKNS_4core9SharedPtrINS_6packet6PacketENS2_15RefCntOwnershipEEE+0x1f5
#12: 0x508a3c9 _ZN3roc5netio15UDPReceiverPort8recv_cb_EP8uv_udp_slPK8uv_buf_tPK8sockaddrj+0x7a7
#13: 0x53114b3 uv_tty_reset_mode+0x5b3
#14: 0x5313340 uv__io_poll+0x400
#15: 0x5303cc8 uv_run+0x118
#16: 0x50861ba _ZN3roc5netio11Transceiver3runEv+0x46
#17: 0x50a1491 _ZN3roc4core6Thread14thread_runner_EPv+0x23
#18: 0x64b46db start_thread+0xdb
#19: 0x5fd588f clone+0x3f
```

Demangled:

```
#1: 0x50a187e roc::core::print_emergency_backtrace()+0x17
#2: 0x50a081c roc::core::(anonymous namespace)::signal_handler(int, siginfo_t*, void*)+0x58
#3: 0x5ef2f20 killpg+0x40
#4: 0x5ef2e97 gsignal+0xc7
#5: 0x5ef4801 abort+0x141
#6: 0x55b785e __cxa_throw_bad_array_new_length+0x4c7
#7: 0x55c34f6 std::rethrow_exception(std::__exception_ptr::exception_ptr)+0x76
#8: 0x55c3541 std::terminate()+0x11
#9: 0x55c426f __cxa_pure_virtual+0x1f
#10: 0x12c33d roc::(anonymous namespace)::Proxy::send_packet_(roc::packet::IReader&, bool)+0x43
#11: 0x12c2bd roc::(anonymous namespace)::Proxy::write(roc::core::SharedPtr<roc::packet::Packet, roc::core::RefCntOwnership> const&)+0x1f5
#12: 0x508a3c9 roc::netio::UDPReceiverPort::recv_cb_(uv_udp_s*, long, uv_buf_t const*, sockaddr const*, unsigned int)+0x7a7
#13: 0x53114b3 uv_tty_reset_mode+0x5b3
#14: 0x5313340 uv__io_poll+0x400
#15: 0x5303cc8 uv_run+0x118
#16: 0x50861ba roc::netio::Transceiver::run()+0x46
#17: 0x50a1491 roc::core::Thread::thread_runner_(void*)+0x23
#18: 0x64b46db start_thread+0xdb
#19: 0x5fd588f clone+0x3f
```

**Comment by gavv** [comment]
`Proxy::send_packet_()` calls two virtual methods: `packet::IReader::read()`, implemented by `packet::Queue`, and `packet::IWriter::write()`, implemented by `netio::UDPSenderPort` returned by `trx_.add_udp_sender()`.

One possible reason of a pure virtual method call is calling a virtual method after destroying the object. Just checked it: http://codepad.org/J5PWyPP6

So probably `send_packet_()` is called when `source_queue_` or `repair_queue_` is already destroyed, or when `UDPSenderPort` is already destroyed.

If the first is true, reordering Proxy fields should fix the issue.

Now it is:

```
    netio::Transceiver trx_;

    ...

    packet::Queue source_queue_;
    packet::Queue repair_queue_;
```

and it should become:

```
    packet::Queue source_queue_;
    packet::Queue repair_queue_;

    ...

    netio::Transceiver trx_;
```

Actually it seems that the current order is incorrect anyway, but before fixing it, we should check whether it is the actual source of the problem or there is also another one :)

If it doesn't fix the issue, the problem is likely with the deinitialization order of UDP senders and receivers in `netio::Transceiver`.

**Comment by gavv** [comment]
@alexandremgo if you're able to reproduce the problem, could you take a look?

**Comment by alexandremgo** [comment]
Yes I'll take a look while working on #278

**Comment by gavv** [comment]
It seems that the problem was caused by the field order in test: https://github.com/roc-project/roc/pull/283#issuecomment-552511362

It will be resolved by that PR.

But before closing this issues, we should re-check whether we have a correct deinitialization order guarantee in Transceiver. Probably we need to fix it too.

**Comment by gavv** [comment]
> But before closing this issues, we should re-check whether we have a correct deinitialization order guarantee in Transceiver. Probably we need to fix it too.

It seems that the port deinitialization order in Transceiver doesn't matter because Transceiver doesn't destroy any objects outside netio. So we can close this issue after merging #283.
