### ISSUE TITLE
Print thread ID in log messages

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#290]
## Problem

It would be convenient to include integral thread identifier in log messages.

Currently messages look like this:

```
13:36:34.803 [dbg] roc_sndio: initializing pulseaudio backend
```

and with thread ID they should look like:

```
13:36:48.977 [7843] [dbg] roc_sndio: initializing pulseaudio backend
```

This thread ID can be used to distinguish threads, and, at least on Linux, to find these threads in ps/top and to send signals to them.

## Solution

We can use `syscall(SYS_gettid)` on Linux and `pthread_getthreadid_np()` on OSX and (in future) on BSD. Both function are non-portable.

Steps:

* Add `target_linux` and `target_bsd` to [SConstruct](https://github.com/roc-project/roc/blob/42ed45ed714488f45ff36483e8baaa4f5f3829cc/SConstruct#L601). `target_linux` should be enabled if `platform` is `linux` or `android`. `target_bsd` should be enabled if `plarform` is `darwin`. 

* Add `core::format_tid()`, similar to `core::format_time()`. It should have two implementations: `src/modules/roc_core/target_linux/roc_core/format_tid.cpp` (using SYS_gettid) and `src/modules/roc_core/target_bsd/roc_core/format_tid.cpp` (using pthread_getthreadid_np).

* Use `core::format_tid()` in `core::Logger::print()`.

**Comment by dshil** [comment]
@gavv, what about using `uv_thread_self`?

**Comment by dshil** [comment]
@gavv, what about using `uv_thread_self`?

**Comment by gavv** [comment]
@dshil it's portable, but, just like pthread_self(), it returns an opaque handle that is not an integral type. It can't be printed, or used to find the thread in ps/top, or used to to send a signal to the thread.

**Comment by gavv** [comment]
Assigned to @RohanK99.
