### ISSUE TITLE
Add openSUSE to travis and docs

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#307]
It would be nice to add openSUSE to CI and docs:

* Create a pull request to our [dockerfiles](https://github.com/roc-project/dockerfiles), adding `travis-opensuse` image. The image will appear on docker hub after merging.

* Add `opensuse.sh` to https://github.com/roc-project/roc/tree/master/scripts/travis/linux-x86_64

* Pull `travis-opensuse` and invoke `opensuse.sh` in https://github.com/roc-project/roc/blob/master/.travis.yml ("Linux x84_64" section)

* Add OpenSUSE build instructions to https://roc-project.github.io/roc/docs/building/user_cookbook.html (https://github.com/roc-project/roc/blob/master/docs/sphinx/building/user_cookbook.rst)

This page may be helpful:

* https://roc-project.github.io/roc/docs/development/continuous_integration.html

**Comment by name213** [comment]
Hey, if it's free, I would like to work on this issue!

**Comment by gavv** [comment]
Sure, you're welcome :)

**Comment by gavv** [comment]
Merged.
