### ISSUE TITLE
Issues building with pulseaudio 13.99.1

### ISSUE THREAD

**Issue by theblazehen** [roc-project/roc#351]
Hi,

I'm trying to build against Pulseaudio 13.99.1, however I'm having issues with that. Tried on master and on develop. It doesn't seem to have that same issue with pulseaudio 13.0

I'm running the build with `scons -Q --enable-pulseaudio-modules --build-3rdparty=openfec,pulseaudio:13.99.1 | tee build.log`

I have attached build.log

Thanks
[build.log](https://github.com/roc-project/roc/files/4551204/build.log)

**Comment by gavv** [comment]
Hi!

The build.log is incomplete, maybe you forgot to include stderr.

But actually I was already working on a fix for building with PulseAudio 13.99, as discussed in https://github.com/roc-project/roc/pull/291#issuecomment-620076469. I've just pushed it to `develop` branch. Could you please check it? If it works, I'll push it to `master`.

(Note that `develop` branch is unstable yet, though it should build and likely works good currently).

**Comment by theblazehen** [comment]
Ah, my bad, yes I didn't include stderr. Development branch works :) Thanks!

Quick question: I've got output working from one endpoint to the other, but it there any way to get one to act as a microphone and the other to see it as an audio input? 

Use case: use my phone as the microphone input audio output for my laptop. Right now I can get the microphone input across as an audio stream with `pacat -r | pacat -p` and using the monitor device as audio input on the remote end, but that's not quite ideal.

Is using `roc-send` on my phone with the microphone source to the roc pulseaudio module on my laptop the best approach?

**Comment by gavv** [comment]
Great, I've pushed the fix to master.

If you want to grab the sound from microphone and send to remote receiver, you can:

* Use roc-send command-line tool. You can specify the input device using `-i` option. It can be PulseAudio source or ALSA capture device, for example.

* Use module-roc-sink PulseAudio module and then connect PulseAudio source of your microphone to the Roc sink using module-loopback PulseAudio module (e.g. search for "Connect a local sink to a remote sink" in [this article](https://gavv.github.io/articles/pulseaudio-under-the-hood/)).

The first solution will work better, but command-line tools are not supported on Android yet (and would not be convenient, though we anyway will add support in future).

The second solution increases the latency. It probably will work on Android, though running PulseAudio on Android in convenient as well.

A better solution using PulseAudio is to provide module-roc-source-output that can be directly connected to a source and act as Roc sender, without using module-loopback. I did not plan to implement one, but why not. Please file an issue if you need it.

A better solution for Android is to provide an Android app that can act both as receiver and sender. This is planned and now we're one step closer to it after merging [java bindings](https://github.com/roc-project/roc-java/) recently.

**Comment by theblazehen** [comment]
Thanks for your feedback!
