### ISSUE TITLE
Reduce probable contention in UdpSenderPort

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#352]
Currently netio::UdpSenderPort::write_sem_cb_() locks the mutex every time it get a packet from the queue.

This is likely okay, but we could perform a small optimization and employ a kind of "double buffering":

* instead of one packet list, use two lists, "writable" and "readable"
* write() writes to "writable" list under a lock
* write_sem_cb_() locks the mutex, swaps "writable" and "readable" lists, unlocks the mutex, and then reads from the "readable" list until it's empty; then repeat until both lists are empty

This optimization will allow to reduce risk of contention on the mutex when the I/O callback is delayed for some reason (e.g. by OS scheduler because of system load or by libuv because of a I/O peak) and then wakes up and starts reading accumulated packets.

In this case frequent mutex locks/unlocks may be unsynchronized with the pipeline thread writes and may lead to a delay in sound I/O (something about a few microseconds for each conflict on average desktop, and likely even more on weaker embedded CPUs). It would be nice to reduce the risk of such situation, given that the optimization is easy to implement.

The same "double list" approach is used here: https://github.com/roc-project/roc/blob/develop/src/modules/roc_pipeline/receiver_endpoint.cpp#L102-L110

It can be used as an example.

**Comment by codeboy5** [comment]
I would like to work on this

**Comment by gavv** [comment]
Thanks, but I forgot to mention that it should be done after #348, which is still in progress (#350).

**Comment by gavv** [comment]
#348 is done, but I'm going to close this issue since I've found a better approach. I'm working on a lock-free queue for #215 and later I'll employ it for UdpSenderPort as well.

@codeboy5 sorry for inconvenience.
