### ISSUE TITLE
Determine maximum acceptable packet loss ratio for FEC decoder

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#43]
Our integration tests with random packet loss of 1% fail from time to time. I guess it's because sometimes, there are to much lost packets _per block_.

I think we should use a fixed number of lost packets per block in such tests.

**Comment by baranovmv** [comment]
Do you mean `TEST(block_codecs, load_test)`?
In this test maximum packets loss limit is 3. It is hardcoded in the tests code.

**Comment by gavv** [comment]
No, [this one](https://github.com/roc-project/roc/blob/master/src/tests/roc_pipeline/test_client_server.cpp#L173) (client/server integration test).

It uses FEC + [`packet::Wrecker`](https://github.com/roc-project/roc/blob/master/src/modules/roc_packet/wrecker.cpp) that drops packets randomly, with loss ration set to 1%.

This test fails from time to time. After configuring CI, this became a problem.

Is it possible to make the test 100% reliable?  Could we drop packets in a such way so that decoder was guaranteed to be able to restore them?

BTW, `load_test` also fails from time to time, but much less often.

**Comment by baranovmv** [comment]
Ok, I'll try to figure out this.
NB: with our default session configuration (20 + 10 packets) losses ratio quantized with step 1/30.

**Comment by gavv** [comment]
Related: #56.

**Comment by baranovmv** [comment]
It seems like the main reason of losses is huge delays in wifi network, that happens on a sudden and lasts for a few hundreds of ms. The problem with them is that the receiver doesn't wait for them and it takes time for the sender to catch up with the receiver again.

Here is an example (streamer's circles with black dots are played packets, empty circles are skipped).
![delays_plot](https://cloud.githubusercontent.com/assets/1952503/24343945/c9a0bcfc-12d1-11e7-98dd-d2c95f39543c.png)

**Comment by gavv** [comment]
But anyway we have to measure two metrics:

1. maximum acceptable packet loss ratio for FEC decoder (both LDPC and Reed-Solomon)
2. average network loss ratio and delays for some typical use cases

With these metrics, we can make our tests stable and choose default latency and packet and block sizes.

This task is for the first point. We need it to fix tests. The second point is a separate task. I've created a new one: #79. The diagram above should be probably moved or copied there.
