### ISSUE TITLE
Get rid of additional output latency in server?

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#46]
Currently, output latency is _added_ to session latency. But is this really required?

**Comment by baranovmv** [comment]
The session latency is size of received packets queue? Output latency consists of FEC and resampler buffers?

**Comment by gavv** [comment]
Session latency is initial size of packet queue. I guess it's value shouldn't be less than FEC block size and resampler frame size (or 3 frames?).

In other words, session latency is delay between receiving a packet and rendering a sample buffer from it.

Output latency is *additional* delay between rendering the sample buffer and sending it to ALSA/pulseaudio. I added this delay to prevent ALSA under-runs, so that when ALSA needs next buffer, it's always available.

When sample buffer is rendered, it's added to sample buffer queue, shared between renderer (`pipeline::Server`) and player (`sndio::Writer`) threads. Output latency is initial size for this queue.

**Comment by gavv** [comment]
Output latency is implemented in [`DelayedWriter`](https://github.com/roc-project/roc/blob/master/src/modules/roc_audio/delayed_writer.h).

**Comment by baranovmv** [comment]
Yes. Packet queue size is hopping permanently between `N` and `N - FEC block size` so it mustn't fall down to zero and `N` must be strictly greater than `FEC block size`.
I guess if `Resamplers frame size` is smaller than `FEC block size` (measured in samples) it doesn't appear in any equations.

**Comment by baranovmv** [comment]
The Sample Buffer Queue is intended to deliver asynchronously samples from renderer thread to player thread, right? If so you can't get rid of this and you can't make it smaller than some constant value greater than zero.
Do I get it right?

**Comment by baranovmv** [comment]
Or you must render samples synchronously with player

**Comment by gavv** [comment]
> The Sample Buffer Queue is intended to deliver samples asynchronously from renderer thread to player thread, right?

Yes.

> Or you must render samples synchronously with player

My quick tests showed that minimum delay of `20 * 320` samples is required to avoid ALSA underruns (maybe it matters that ALSA works over pulseaudio on my system).

I wasn't able to avoid underruns with smaller delays or when rendering samples and sending them to ALSA in the same thread.

I think the delay may be reduced, but I don't think we can completely eliminate it. Currently we're using SoX. We can play with sox parameter or maybe with [ALSA parameters](https://github.com/gavv/snippets/blob/master/decode_play/alsa_play_tuned.cpp) directly.

> If so you can't get rid of this and you can't make it smaller than some constant value greater than zero.

Yes, we can't eliminate output delay (I think). And we can't eliminate session delay (it's essential).

But are they required to to be *summed*? I'm wondering if there is a way to convert this:

```
+--------------+-----------------+-------+
| output delay |  session delay  | sound |
+--------------+-----------------+-------+
```

to this:

```
+-----------------+-------+
|  session delay  | sound |
+--+--------------+-------+
   | output delay |
   +--------------+
```

Though I have no idea how we could implement this, it seems to me that it's possible.

**Comment by gavv** [comment]
In other words, do we need to insert `output_delay + session_delay` zero samples before playing sound? Is there a way to insert `max(output_delay, session_delay)` zero samples instead?

**Comment by gavv** [comment]
PS. when using pulseaudio backend, minimum required output delay is much lower. I didn't try to sort it out (yet).

**Comment by baranovmv** [comment]
* You must have samples in output queue *before* play.
* You must render this samples before putting them to output queue.
* In order to render them with minimum error probability you must use FEC so you must use session queue and so on.

**Comment by gavv** [comment]
> In order to render them with minimum error probability you must use FEC so you must use session queue and so on.

I missed that. I was thinking about some tricky pre-rendering, but you're right, we can't do this.

Well, then we should concentrate on reducing output latency.

**Comment by gavv** [comment]
It seems that we can live without additional output queue at all. The receiver pipeline is now integrated into SoX thread.

Current solution works with pulseaudio, bare ALSA, and CoreAudio, so I'm closing this.
