### ISSUE TITLE
Practical recommendations for LDPC FEC Scheme

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#56]
Extracted from [Section 7.1](https://tools.ietf.org/html/rfc6816#section-7.1) of [RFC 6816](https://tools.ietf.org/html/rfc6816). See also #48.
### Block size

> LDPC-Staircase codes have excellent erasure recovery capabilities
>    with large source blocks, close to ideal MDS codes.  For instance,
>    independently of FECFRAME, let us consider a source block of size
>    k=1024 symbols, CR=2/3 (i.e., 512 repair symbols are added), N1=7,
>    G=1, a transmission scheme where all the symbols are sent in a random
>    order, and a hybrid ITerative/Maximum Likelihood (IT/ML) decoder (see
>    below).  An ideal MDS code with code rate 2/3 can recover from
>    erasures up to a 33.33% channel loss rate.  With LDPC-Staircase
>    codes, the average overhead amounts to 0.237% (i.e., receiving 2.43
>    symbols in addition to k, which corresponds to a 33.18% channel loss
>    rate.
> 
> [...]
> 
> As the source block size decreases, the erasure recovery capabilities
>    of LDPC codes in general also decrease.
> 
> [...]
> 
> With very small source blocks (e.g., **a few tens of symbols**), using
>    for instance Reed-Solomon codes [SIMPLE_RS] or 2D parity check codes
>    may be more appropriate.

These notes raised two question for me:
- Should we try smaller packet sizes with larger number of packets per block?
- Should we also try Reed-Solomon codes?

BTW, Raptor(Q) support for FECFRAME includes several schemes, with some of them dedicated specially for small block size case.
### Interleaving

And a note related to our `Interleaver`:

> The way the FEC repair packets are transmitted is of high importance.
>    A good strategy, that works well for any kind of channel loss model,
>    consists in sending FEC repair packets in random order (rather than
>    in sequence) while FEC source packets are sent first and in sequence.
>    Sending all packets in a random order is another possibility, but it
>    requires that all repair symbols for a source block be produced
>    first, which adds some extra delay at a sender.

Should we reconsider our interleaving scheme?

**Comment by gavv** [comment]
We've added support for Reed-Solomon codec. What's left:

* We should make FEC codec selectable via command line.
* We should support separate interleaving schemes for source and repair packets.
* We should choose optimal default latency, block size, and interleaving scheme.

**Comment by baranovmv** [comment]
* FEC codec options are defined here #6 
* Interleaving schemes are also described here #6 

I guess we should build effective logging for packets passing timing, which should be output to a file and / or be available from inside the program in order to:
- to be able to plot the graphs of the queues length (latency);
- to tune the latency and the size of a FEC block automatically.

**Comment by gavv** [comment]
The #69 task is about debug logging. I've created a separate task for packet logging (and more), see #78.

**Comment by gavv** [comment]
All issues will be covered by #6 and #79, so closing this.
