### ISSUE TITLE
Get rid of hardcoded parameters in roc_fec

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#6]
In current implementation, the following encoder/decoder parameters are configured at compile time:
- block size (number of data and FEC packets in block);
- packet size (number of bytes in audio packet).

They are:
- `ROC_CONFIG_DEFAULT_FEC_BLOCK_DATA_PACKETS`
- `ROC_CONFIG_DEFAULT_FEC_BLOCK_REDUNDANT_PACKETS`
- `ROC_CONFIG_DEFAULT_PACKET_SIZE`

Moreover, if server and client are built with different parameters, server may behave incorrectly.

What we need instead:
- configure parameters at runtime (when creating encoder/decoder), and use `ROC_CONFIG_` values just as defaults;
- handle possibility of parameters mismatch;
- provide corresponding runtime configuration options in `ServerConfig` and `ClientConfig` in `roc_pipeline`;
- use smaller packet size in client/server tests to make them faster.

**Comment by baranovmv** [comment]
Its better to produce something compatible with [RFC5170](https://tools.ietf.org/html/rfc5170#section-4.2)

**Comment by gavv** [comment]
That is, LDPC packets already contain # of data/fec packets in block?

What about packet size? Can we e.g. auto-detect it from first packet passed to encoder/decoder? (this will require lazy initialization of openfec codec instance).

In this case, we can get rid of *any* options in decoder (we still need configurable block sizes for encoder).

**Comment by gavv** [comment]
#13

**Comment by baranovmv** [comment]
[Asynchronous Layered Coding (ALC)](https://tools.ietf.org/html/draft-ietf-rmt-pi-alc-revised-10)
[FLUTE - File Delivery over Unidirectional Transport](https://tools.ietf.org/html/draft-ietf-rmt-flute-revised-16)

**Comment by gavv** [comment]
Could you give a brief overview of formats used by LDPC codec from OpenFEC and their relation to RFC5170?

We probably should document it on wiki or in README... ("supported protocols" section)

**Comment by baranovmv** [comment]
Ok

**Comment by gavv** [comment]
I've started working on #48, after which can resolve this issue too.

**Comment by gavv** [comment]
### [RFC 6816: LDPC FEC Scheme for FEC Framework](https://tools.ietf.org/html/rfc6816)

Extracted from [Section 5.1.1](https://tools.ietf.org/html/rfc6816#section-5.1.1).

**FEC Scheme-Specific Information**

RFC 6816 requires the following parameters to be communicated from sender to receiver:

* FEC Encoding ID (constant identifying LDPC Scheme, registered in IANA)
* PRNG seed
* Encoding symbol length (maximum or fixed packet size, depending on *strict flag*)
* Strict flag (defines whether packet size is fixed or not)
* N1M3 (codec configuration)

**Source FEC Payload ID**

The RFC also requires the following parameters to be included within every source packet:

* Source Block Number (SBN)
* Encoding Symbol ID (ESI), packet number *inside its block*
* Source Block Length (k), number of *source* packets in block

**Repair FEC Payload ID**

And within every repair packet:

* Source Block Number (SBN)
* Encoding Symbol ID (ESI)
* Source Block Length (k), number of *source* packets in block
* Number of Encoding Symbols (n), number of *source and repair* packets in block

The RFC suggests implementation to append a 6-byte footer (Source FEC Payload ID) to every source packet and 8-byte header (Repair FEC Payload ID) to every repair packet.

**Comment by gavv** [comment]
FEC Scheme-Specific Information (FSSI) may be communicated over SDP.

However, we have no SDP support yet. so we can start with making the following parameters configurable through command line:
* Encoding symbol length (packet size)
* PRNG seed
* N1M3

**Comment by gavv** [comment]
We also should decide how we will communicate Source FEC Payload ID and Repair FEC Payload ID from sender to receiver within every packet.

Possible options are:
* add explicit footer/header to every source/repair packet, or
* use RTP header and dynamically derive this information from RTP header at receiver.

In any case, we should adopt `fec::Decoder` to use dynamic block and packet sizes available within every received packet.

**Comment by gavv** [comment]
**Note about OpenFEC**

OpenFEC encoder and decoder work with *symbols*, not packets. Those symbols don't include Source FEC Payload ID and Repair FEC Payload ID, and it's up to the applications (i.e., us) to communicate them within packets.

**Comment by gavv** [comment]
See also client/server example in OpenFEC sources. They add additional header with block sizes to every packet (though not compliant with any RFC, as mentioned in comments).

**Comment by gavv** [comment]
### Packet formats suggested in RFC 6816

(in case when RTP is *not* used for repair packets)

**Source FEC Payload ID**

```
                  +--------------------------------+
                  |           IP Header            |
                  +--------------------------------+
                  |        Transport Header        |
                  +--------------------------------+
                  |              ADU               |
                  +--------------------------------+
                  | Explicit Source FEC Payload ID |
                  +--------------------------------+

Explicit Source FEC Payload ID:

    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |   Source Block Number (SBN)   |   Encoding Symbol ID (ESI)    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    Source Block Length (k)    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Repair FEC Payload ID**

```
                  +--------------------------------+
                  |           IP Header            |
                  +--------------------------------+
                  |        Transport Header        |
                  +--------------------------------+
                  |     Repair FEC Payload ID      |
                  +--------------------------------+
                  |         Repair Symbol          |
                  +--------------------------------+

Repair FEC Payload ID:

    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |   Source Block Number (SBN)   |   Encoding Symbol ID (ESI)    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    Source Block Length (k)    |  Number Encoding Symbols (n)  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Our use-case**

* Transport Header - UDP header
* ADU - RTP packet with RTP header
* Repair Symbol - blob generated by OpenFEC

Note that there is no RTP header in repair packet here.

**Comment by gavv** [comment]
See my comment [here](https://github.com/roc-project/roc/issues/48#issuecomment-172107342). Specifically this issue, we should do the following:

- [ ] Make the following parameters configurable through command line:
 - Encoding symbol length (source packet size)
 - PRNG seed
 - N1M3

- [ ] Adopt `fec::Decoder` to use dynamic block and packet sizes available within every received packet.
  (we need to finish #48 before)

**Comment by baranovmv** [comment]
**`Encoder` and `Decoder` are configurable with this params so far:**
- Number of source packets per block
- Number of repair packets per block
- FEC type (Reed-Solomon, LDPC, ...)
- Options for **LDPC**:
    - PRNG seed
    - N1
- Options for **Reed-Solomon**:
    - m[2|8]

These parameters must have the same values on a sender and a receiver, no matter what the scheme of configuration / negotiation is.

**`Encoder` also has these parameters**:
- Send data packets in order or shuffled (FEC packets should be shuffled anyway);
- Send FEC-packets immediately or interleaved with the next block data packets.

**Comment by gavv** [comment]
> Encoder and Decoder are configurable with this params so far

I think we need fec::EncoderConfig and fec::DecoderConfig or something like this. We can then include it into pipeline::ClientConfig and pipeline::ServerConfig.

Are these setting generic or OpenFEC-specific?

> Encoder also has these parameters

We should use two separate PacketWriters in fec::Encoder for source and repair packets. Then we can implement various interleaving schemes in pipeline::Client. There is no need to hardcode them in Encoder.

**Comment by gavv** [comment]
Also, the FEC scheme (and probably some other parameters) should be configurable via command line.

**Comment by baranovmv** [comment]
Doubts:
* These options determine a behaviour of `IBlockEncoder` and `IBlockDecoder` mainly, but the numbers of source and repair packets are needed in `Encoder` and `Decoder` too. If we make `BlockEncoderConfig` and `BlockDecoderConfig`, `Encoder` and `Decoder` could ask inner block_coder for packets numbers.
* Dividing this options between Encoder and Decoder forces us to use different variables for values that must be equal by design.

**Comment by baranovmv** [comment]
Block Coders [agregate](https://github.com/roc-project/roc/blob/develop/src/modules/roc_fec/target_openfec/roc_fec/of_block_encoder.h#L78-L79) array of pointers with length of **N_DATA_PACKETS + N_FEC_PACKETS** for OpenFEC. How do we instantiate it dynamically?

**Comment by gavv** [comment]
> If we make BlockEncoderConfig and BlockDecoderConfig, Encoder and Decoder could ask inner block_coder for packets numbers.

Yes, sounds reasonable. It'll guarantee that the block encoder and encoder always use the same numbers.

> Dividing this options between Encoder and Decoder forces us to use different variables for values that must be equal by design.

It's probably OK since encoder and decoder are anyway instantiated on different computers :)

> Block Coders agregate array of pointers with length of N_DATA_PACKETS + N_FEC_PACKETS for OpenFEC. How do we instantiate it dynamically?

I think since it's unlike that we want huge block sizes, we can define a macro in config.h with maximum block size and use it as the Array template argument. Then we'll pass the real block size to the Array constructor.

**Comment by gavv** [comment]
We're done here.
