### ISSUE TITLE
Enable CPU timer when and only when working with files

### ISSUE THREAD

**Issue by baranovmv** [roc-project/roc#63]
There is a doubt if it is correct to feed sample queue between threads by absolute timer

**Comment by gavv** [comment]
PulseAudio and ALSA clock clients in the sound card domain. So we should disable our own timing when writing sound to a local device.

We still need our own timing when sending samples over RTP/UDP.

CUrrently, timing is enabled or disabled manually by user (via command line option). We should do it automatically instead.

**Comment by baranovmv** [comment]
- This automation should be implemented in **roc/tools** only.
-  CAPI is to be provided by `self_timning` argument of its `*_open` functions.

**Comment by gavv** [comment]
See also #100.

**Comment by gavv** [comment]
### TODO

- [ ] roc-recv
- [ ] roc-send
