### ISSUE TITLE
Sample rate conversion in roc_recv

### ISSUE THREAD

**Issue by baranovmv** [roc-project/roc#85]
Due to #84, the Roc will be able to convert a sample rate of received signal on its own. For that purpose some changes in the other part of the code should be made:

* The Resampler's scaling factor should be properly adjusted according to the information from the RTP-packet headers and the sample rate of the renderer.
* The renderer (such as SoX) should provide the output sample rate to the other part of the code.

**Comment by gavv** [comment]
So, the plan:

- [ ] sndio::Writer should report the output sample rate
- [ ] pipeline::Session should obtain the output sample rate
- [ ] some component in the session pipeline should obtain the input sample rate from the first received RTP packet
- [ ] the Resampler scaling factor should be adjusted according to the output sample rate and input sample rate

**Comment by gavv** [comment]
We likely also want two new command line options:

- [ ] output sample rate in roc-recv (the user may want to set it when writing to a file or when the sound card sample rate was detected incorrectly)

- [ ] network sample rate in roc-send (the user may want values other than 44100, e.g. to avoid unnecessary resampling; currently, we use SoX to unconditionally resample input samples to 44100)

**Comment by gavv** [comment]
This issue will fix #61.

**Comment by gavv** [comment]
Finally done.
