### ISSUE TITLE
Add support for Raspberry Pi

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#9]
- [x] cross compilation
- [x] warnings
- [x] running
- [x] ci
- [x] instructions

**Comment by gavv** [comment]
Playback problems on Raspberry Pi:


Backend        | With Resampler | Without Resampler |
---------------|----------------|-------------------|
SoX/Pulseaudio | bad            | ok
SoX/ALSA       | bad            | bad: #61, #62
Direct ALSA    | ok             | ok

**Comment by gavv** [comment]
Note that we can't play at all if `Resampler` is enabled and `debug` build is used. Only `release` build works.

**Comment by gavv** [comment]
Building toolchain for Raspberry Pi A in Gentoo:

```
crossdev -S -v -t armv6j-hardfloat-linux-gnueabi --libc 2.19
```

**Comment by gavv** [comment]
Building toolchain for *Orange Pi One* in Gentoo:

```
emerge -v =sys-devel/make-3.8*
layman -a toolchain

mkdir -p /etc/portage/patches/cross-armv7a-hardfloat-linux-gnueabi/glibc
cat > /etc/portage/patches/cross-armv7a-hardfloat-linux-gnueabi/glibc/nosp.patch
--- /dev/null	2016-05-15 11:33:43.820023781 +0300
+++ configparms	2016-05-16 17:46:22.160347362 +0300
@@ -0,0 +1 @@
+CFLAGS += -fno-stack-protector
^D

crossdev -S -v -t armv7a-hardfloat-linux-gnueabi --libc '=2.13*'
```

You need `-fno-stack-protector` flag to build glibc 2.13 (which is used is Raspbian for Orange Pi) with uptodate GCC. See details here: [1](https://sourceware.org/ml/libc-help/2008-07/msg00075.html), [2](http://klaig.blogspot.ru/2011/07/how-to-apply-user-patches-in-portage.html).

**Comment by gavv** [comment]
[Toolchain tuples](https://wiki.gentoo.org/wiki/Embedded_Handbook/Tuples)

**Comment by gavv** [comment]
[Multiarch Tuples](https://wiki.debian.org/Multiarch/Tuples)

**Comment by gavv** [comment]
[Uname](https://en.wikipedia.org/wiki/Uname)

**Comment by gavv** [comment]
[Autoconf: Specifying Target Triplets](https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Specifying-Target-Triplets.html)

**Comment by gavv** [comment]
@baranovmv 

Could you try [this instructions](https://github.com/roc-project/roc/wiki/Building-%28cross-compile%29#raspberry-pi-1-armv6) and cross-compile Roc for your RPi A?

Both "Manually" and "Docker" sub-sections of "Raspberry Pi 1" section.

It's also interesting if [debian-way approach](https://github.com/roc-project/roc/wiki/Building-%28cross-compile%29#ubuntu-and-debian-armhf-armv7) ("Ubuntu and Debian armhf" section) works for you?

(Doesn't work for my OPi, because `crossbuild-essential-armhf` builds binary that requires newer Glibc than on my box.)

**Comment by gavv** [comment]
[Emulating ARM in QEMU](https://github.com/roc-project/roc/wiki/Emulating-ARM-in-QEMU)

**Comment by gavv** [comment]
I've created new task #68 for performance problems. Thus, we can close this task when our cross-compiling will work for RPi A.

**Comment by gavv** [comment]
Everything works on Orange Pi.

**Comment by baranovmv** [comment]
Any crossbuild technique for Raspberry Pi A  works well.
